# Generated by Django 4.1.2 on 2022-11-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
        ('Outings', '0002_remove_outing_costs_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='beneficient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficient', to='Profiles.profile'),
        ),
        migrations.AddField(
            model_name='expense',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to='Profiles.profile'),
        ),
        migrations.RemoveField(
            model_name='outing',
            name='participants',
        ),
        migrations.AddField(
            model_name='outing',
            name='participants',
            field=models.ManyToManyField(blank=True, to='Profiles.profile'),
        ),
    ]
